---
title: "Untitled"
author: "Marjorie Blanco"
date: "1/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set
library(arules)
library(vcd)
library(knitr)
```

## The Titanic Dataset

```{r}
load("~/GitHub/modeling/titanic.raw.rdata")
# mosaic(titanic.raw, 
#        gp = shading_hcl,
#        gp_args = list(interpolate = c(1, 1.8)))

```


```{r}
# library(caret)
# 
# set.seed(123)
# trainIndex <- createDataPartition(titanic.raw$Survived, p = .8, 
#                                   list = FALSE, 
#                                   times = 1)
# head(trainIndex)
```

```{r}
idx <- sample(1:nrow(titanic.raw), 5)
titanic.raw[idx,]
summary(titanic.raw)
```
## Association Rule Mining


```{r}
rules.all <- apriori(titanic.raw)
inspect(rules.all)
```

```{r}
#rules with rhs containing "Survived" only
rules <- apriori(titanic.raw,
                control = list(verbose = F),
                 parameter = list(minlen = 2, supp = 0.005, conf = 0.8),
                 appearance = list(rhs=c("Survived=No",
                                         "Survived=Yes"),
                                   default="lhs"))

#keep three decimal places
quality(rules) <- round(quality(rules), digits = 3)

#order three decimal places
rules.sorted <- sort(rules, by="lift")

inspect(rules.sorted)
```
```{r}
inspect(rules.sorted[1:2])
```

## Remove redundant rules

```{r}
# find redundant rules
subset.matrix <- is.subset(rules.sorted, rules.sorted)
#subset.matrix[lower.tri(subset.matrix, diag = T)] <- TRUE
redundant <- colSums(subset.matrix, na.rm=T) >= 1

# which rules are redundant
which(redundant)
# remove redundant rules
rules.pruned <- rules.sorted[!redundant]
```

## Remaining rules

```{r}
#inspect(rules.pruned)
#inspect(rules.pruned[1])
```

## Rules about children

```{r}
# rules <- apriori(titanic.raw,
#                 control = list(verbose = F),
#                  parameter = list(minlen = 3, supp = 0.002, conf = 0.2),
#                                    rhs=c("Survived=Yes"),
#                                    lhs=c("Class=1st",
#                                          "Class=2nd",
#                                          "Class=3rd",
#                                          "Age=Child",
#                                          "Age=Adult"))

rules <- apriori(titanic.raw,
                 parameter = list(minlen=2, supp=0.005, conf=0.8),
                 appearance = list(rhs=c("Survived=No", "Survived=Yes"),
                                   default="lhs"),
                 control = list(verbose=F))
```

## Visualizing association rules

```{r}
library(arulesViz)
rules.sorted <- sort(rules, by = "confidence")
kable(inspect(rules.sorted))
plot(rules.sorted)
plot(rules.sorted, method="grouped")
plot(rules.sorted, method="graph", control=list(type="items"))
plot(rules.sorted, method="paracoord", control=list(reorder=TRUE))
```

```{r}
plot(rules.all, method="graph")
```

```{r}
plot(rules.all, method = "graph", control = list(type="items"))
```

```{r}
plot(rules.all, method="paracoord", control = list(reorder = TRUE))
```

```{r}
library("arulesViz")
data(Groceries)

rules <- apriori(Groceries, parameter=list(support=0.001, confidence=0.5), 
                 control=list(verbose=FALSE))
inspect(head(sort(rules, by ="lift"),3))

plot(rules, method="matrix", measure="lift")
plot(rules, method="matrix3D", measure="lift")

subrules <- head(sort(rules, by="lift"), 10)
plot(subrules, method="graph", control=list(type="items"))

plot(rules, method="grouped", control=list(k=20))
```


```{r}
library(readr)
library(dplyr)
library("arulesViz")

adult <- read_csv("Data sets/Clem3Training.csv")
adult <- filter(adult, workclass != "?")

adult  <- adult[, c(2,6,10,15)]
adult$workclass <- factor(adult$workclass)
adult$`marital-status` <- factor(adult$`marital-status`)
adult$sex <- factor(adult$sex)
adult$income <- factor(adult$income)

adult %>% filter(`marital-status` == "Never-married", workclass == "Private", income == "<=50K.") %>% count()


adult %>% filter(`marital-status` == "Never-married", income == "<=50K.") %>% count()
adult %>% filter(`marital-status` == "Never-married") %>% count()

adult %>% filter(sex == "Female", income == "<=50K.") %>% count()


rules <- apriori(adult,
                control = list(verbose = F),
                parameter = list(minlen = 2, supp = 0.15, conf = 0.8),
                appearance = list(rhs=c("income=<=50K.", "income=>50K."),
                default="lhs"))

rules
```

Minimum support: 15% Minimum confidence: 80% Maximum of two antecedents
```{r}
inspect(head(sort(rules, by ="lift"), 5))
```

```{r}

rules.sorted <- sort(rules, by = "confidence")
kable(inspect(rules.sorted))
plot(rules.sorted)
plot(rules.sorted, method="grouped")
plot(rules.sorted, method="graph", control=list(type="items"))
plot(rules.sorted, method="paracoord", control=list(reorder=TRUE))
plot(rules, method="matrix3D", measure="lift")
```

